[package]
name = "vxbot"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
dotenvy = "0.15.7"
futures = "0.3.31"
regex = "1.11"
serenity = "0.12.4"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"]}
